boxer <- readDNAStringSet("boxer.fasta")
dalmation <- readDNAStringSet("dalmation.fasta")
golden <- readDNAStringSet("golden.fasta")
golden2 <- readDNAStringSet("golden2.fasta")
lab <- readDNAStringSet("lab.fasta")
dogseq <- c(boxer, dalmation, golden, golden2, lab)
names(dogseq) <- c("b","d","g","g2","l")
dogaln <- msa(dogseq, method=("ClustalW"),cluster="default",type="dna")
print(dogaln, show="complete")
gc_content <- letterFrequency(dogseq, letters = "GC", as.prob = TRUE) 
head(gc_content)
dogalnseq <- msaConvert(dogaln, type="seqinr::alignment")
ddist <- dist.alignment(dogalnseq, "identity")
as.matrix(ddist)
goldendna <- DNAString("TGTTTTCACACCCACGTGATCTCCATGGGGATTGGCGCCCACAGCCCCACACCCCCTCCCCAGCTCACTGGCTCTGTCCTGCCCCCCAGAGAAGAAGCTAGAGGTGTACCAGAGCATTGCGGACCTGACGGTGGGCGCGAAGGACCAGGCGGTGTTCAAGTGTGAGGTGTCCGACGAGAATGTGCGGGGCGTGTGGCTGAAGAACGGGAAGGAGCTGGTGCCTGATAGCCGCATAAAGGTGTCC")
aagolden <- Biostrings::translate(goldendna)
Alignment_phyDat <- msaConvert(Alignment, type="phangorn::phyDat")
write.phyDat(Alignment_phyDat, "alignment.fasta", format = "fasta")
